# Generated by Django 5.1.5 on 2025-01-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0002_portfoliomodel_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalSkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=64, verbose_name='language')),
                ('value', models.IntegerField(verbose_name='percentage %')),
            ],
            options={
                'verbose_name': 'ProfessionalSkill',
                'verbose_name_plural': 'ProfessionalSkills',
            },
        ),
        migrations.CreateModel(
            name='TechnicalSkillsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(max_length=64, verbose_name='language')),
                ('value', models.IntegerField(verbose_name='percentage %')),
            ],
            options={
                'verbose_name': 'TechnicalSkill',
                'verbose_name_plural': 'TechnicalSkills',
            },
        ),
    ]
