# Generated by Django 5.1.5 on 2025-01-22 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0003_professionalskillsmodel_technicalskillsmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionalskillsmodel',
            name='lang',
        ),
        migrations.AddField(
            model_name='professionalskillsmodel',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='title'),
            preserve_default=False,
        ),
    ]
