# Generated by Django 5.1.5 on 2025-01-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0004_remove_professionalskillsmodel_lang_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioTagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='portfoliomodel',
            name='tags',
            field=models.ManyToManyField(related_name='portfolios', to='app_pages.portfoliotagmodel', verbose_name='tag'),
        ),
    ]
