# Generated by Django 5.1.5 on 2025-01-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0006_clientmodel_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('year', models.CharField(max_length=128, verbose_name='year')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'Education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.CreateModel(
            name='WorkLanguageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Work Language',
                'verbose_name_plural': 'Work Languages',
            },
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='image',
            field=models.ImageField(upload_to='client', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='job',
            field=models.CharField(max_length=128, verbose_name='job'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='name',
            field=models.CharField(max_length=128, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.CharField(max_length=128, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='first_name'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='image1',
            field=models.ImageField(upload_to='portfolio', verbose_name='image1'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='image2',
            field=models.ImageField(upload_to='portfolio', verbose_name='image2'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='language',
            field=models.CharField(max_length=128, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='title',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='portfoliomodel',
            name='url',
            field=models.CharField(max_length=255, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='portfoliotagmodel',
            name='title',
            field=models.CharField(max_length=128, verbose_name='title'),
        ),
        migrations.CreateModel(
            name='WorkExperienceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('year', models.CharField(max_length=128, verbose_name='year')),
                ('languages', models.ManyToManyField(to='app_pages.worklanguagemodel')),
            ],
            options={
                'verbose_name': 'Work Experience',
                'verbose_name_plural': 'Work Experiences',
            },
        ),
    ]
