# Generated by Django 5.1.5 on 2025-01-25 08:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pages', '0007_educationmodel_worklanguagemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='educationmodel',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperiencemodel',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=255, verbose_name='url'),
            preserve_default=False,
        ),
    ]
